{% set name = "xmlschema" %}
{% set version = "2.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2eb426c5710833a05610c22c8766713a1b87e9405e3eca0b7c658375bf7ec810

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - xmlschema-validate=xmlschema.cli:validate
    - xmlschema-xml2json=xmlschema.cli:xml2json
    - xmlschema-json2xml=xmlschema.cli:json2xml

requirements:
  host:
    - python
    - pip
    - elementpath 4.1.4
    - setuptools
    - wheel
  run:
    - python
    - elementpath >=4.1.2,<5.0.0

test:
  imports:
    - xmlschema
  source_files:
    - tests
  requires:
    - jinja2
    - lxml
    - pip
  commands:
    - pip check
    - xmlschema-validate --help
    - xmlschema-xml2json --help
    - xmlschema-json2xml --help
    - python tests/test_all.py

about:
  home: https://github.com/sissaschool/xmlschema
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An XML Schema validator and decoder
  description: |
    This is an implementation of XML Schema for Python 3.7+.

    This library arises from the needs of a solid Python layer for processing
    XML Schema based files for MaX (Materials design at the Exascale) European
    project. A significant problem is the encoding and the decoding of the XML
    data files produced by different simulation software. Another important
    requirement is the XML data validation, in order to put the produced data
    under control. The lack of a suitable alternative for Python in the
    schema-based decoding of XML data has led to build this library. Obviously
    this library can be useful for other cases related to XML Schema based
    processing, not only for the original scope.

  dev_url: https://github.com/sissaschool/xmlschema
  doc_url: https://xmlschema.readthedocs.io/

extra:
  recipe-maintainers:
    - ccwang002
