travis:
  secure:
    BINSTAR_TOKEN: L//w+YeqCJ8Q5mtOK66tDYwGyekPsl3NzDSuIf7QxZQXHAAn+dnb9cCU8M7SP4ETa6C/FiY3D0xa1HXIvp3+K1mcr6Uq5e5+BEVeLtZwYOQcZBZGZ8SAbwbSxGMC/mbyfBE/LWk28dEsHEbh+gtm2CIj67IZGQYXOmLxL46mMtOvAF7uPrNPX0Ba09EGdlT+83fd7qfztAAh4kl88a+Xayb4NSC+sMbeQmhX9tcux2QdscQdq9unqKwJGphYuCO4Xur9XW94a9n4w06pm9A/Gg88hPvoH1E4Pwl3ROIKQA4NOquiDYbkFoKbN5WNrNB6WK/rzmWDk2+lY+UOcAxjhtnbPL+y38b41m4az8koDtGDDvEbhBilyIijYqcm04frR+ScBmnwcI0ncn8uNn7UniaxhLvfYK7xP2iPfGTuzdBuGmpy1D0uwUaQtxGzMrmp9bjEABXliLqr0hUAcLYp/Ft4vk+oMEKGbipnAec6Xzho1GWSL18Nc76/fEtZ24iaam1mzj/dpXNtC1Tf7lkJPsTCxkmI/IIRpE76iFMuI6ATNfdn9802har/n1JUhPLTb7OxazTLwmylcGHFFEKAevunWafylTGLHuofr2gOhN3myeEDhzdbmXX8LxEDKAddE23qZASM9HsYFVXapKYZKFGIQUHdmfXvWiMQPgmgbpk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
