travis:
  secure:
    BINSTAR_TOKEN: RBcaGdhdAeUClwnIdmvthOvWVLLIRHtQxNNPyVsNW4olYczYHiFHObuvmhKiQHIKwtOGl24CDPJ9E8jczrKj+YKfmwngfan/mF5m5fsDJxeilaJ4eNA8b+r323vb8/9I6V6hrdcgemNndT+4nrz/HI0+aoAsMejSp2VcQF8eYWK3HBOzWFuHv4bkwLVpa2m6BHdEgAufs1hPCcr/3xZ22wAhnP6ijtRpzSytUv1UKRQv/Nj8eR+/akoqnHUTWttfzGAh4dMlUYNuoUB+B9VYvlMaItcCWsiXfESos8qJ5ZjbIezVdcehNlLQsVpswelcBCjx2MUJMgevsGdSEoPsFSSYeNv+PPY7SsAzYvHAzkDFgC4tHSh2zXlmJ1p9HyWMk3xJ+sTKsdGdAjkEs3f6Zteu6z3fGfjszJP0E0FKcVk+ymRcv3CZsyfPAsTM56F1koWCPApWYwY8VzVqEBtJkupE/wk8I6mUlRYW5xLZzCGxNfMdcUE7Z/DQSWQVvEj5ejwCO0y7ZKmIO45uCCyw9lLIbQfyM/8I/dY77vGdBYdDvpdFFtI71Wwvq+qaZi5Qv6TW/Qb9YMkWrazzar59Ypdyy2/bUOR040lPWBO6z+m3Ol0x8SdRZnxv+hGxCyubpZi9GrFHLZ+YVAQIHL62Ui32AIRA3wb8wZEMfnAPbZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
